/*
* generated by Xtext
*/
package dk.itu.ecdar.text.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import dk.itu.ecdar.text.services.EcdarTextGrammarAccess;

public class EcdarTextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EcdarTextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected dk.itu.ecdar.text.parser.antlr.internal.InternalEcdarTextParser createParser(XtextTokenStream stream) {
		return new dk.itu.ecdar.text.parser.antlr.internal.InternalEcdarTextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ETFile";
	}
	
	public EcdarTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EcdarTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
