/*
* generated by Xtext
*/
package dk.itu.ecdar.text.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EcdarTextAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("dk/itu/ecdar/text/parser/antlr/internal/InternalEcdarText.tokens");
	}
}
