/*
* generated by Xtext
*/
package org.uppaal.xml.description.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.uppaal.xml.description.services.DescriptionGrammarAccess;

public class DescriptionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DescriptionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.uppaal.xml.description.parser.antlr.internal.InternalDescriptionParser createParser(XtextTokenStream stream) {
		return new org.uppaal.xml.description.parser.antlr.internal.InternalDescriptionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Top";
	}
	
	public DescriptionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DescriptionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
