/*
 * generated by Xtext
 */
package org.uppaal.xml.description;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DescriptionRuntimeModule extends org.uppaal.xml.description.AbstractDescriptionRuntimeModule {

}
