/*
* generated by Xtext
*/
package dk.itu.ecdar.text;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EcdarTextUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return dk.itu.ecdar.text.ui.internal.EcdarTextActivator.getInstance().getInjector("dk.itu.ecdar.text.EcdarText");
	}
	
}
