/*
 * generated by Xtext
 */
package dk.itu.ecdar.text;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EcdarTextRuntimeModule extends dk.itu.ecdar.text.AbstractEcdarTextRuntimeModule {

}
