/*
* generated by Xtext
*/
package dk.itu.ecdar.text.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import dk.itu.ecdar.text.services.EcdarTextGrammarAccess;

public class EcdarTextParser extends AbstractContentAssistParser {
	
	@Inject
	private EcdarTextGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected dk.itu.ecdar.text.ui.contentassist.antlr.internal.InternalEcdarTextParser createParser() {
		dk.itu.ecdar.text.ui.contentassist.antlr.internal.InternalEcdarTextParser result = new dk.itu.ecdar.text.ui.contentassist.antlr.internal.InternalEcdarTextParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getETDeclarationAccess().getAlternatives(), "rule__ETDeclaration__Alternatives");
					put(grammarAccess.getETInitialiserAccess().getAlternatives(), "rule__ETInitialiser__Alternatives");
					put(grammarAccess.getETTypeIdentifierAccess().getAlternatives(), "rule__ETTypeIdentifier__Alternatives");
					put(grammarAccess.getETActionTypeAccess().getAlternatives(), "rule__ETActionType__Alternatives");
					put(grammarAccess.getETPrimarySpecificationExpressionAccess().getAlternatives(), "rule__ETPrimarySpecificationExpression__Alternatives");
					put(grammarAccess.getETSpecificationAccess().getAlternatives(), "rule__ETSpecification__Alternatives");
					put(grammarAccess.getETSpecificationDefinitionAccess().getAlternatives(), "rule__ETSpecificationDefinition__Alternatives");
					put(grammarAccess.getETEdgeAccess().getAlternatives_1(), "rule__ETEdge__Alternatives_1");
					put(grammarAccess.getETEdgeAccess().getAlternatives_1_0_9(), "rule__ETEdge__Alternatives_1_0_9");
					put(grammarAccess.getETEdgeAccess().getAlternatives_1_1_3(), "rule__ETEdge__Alternatives_1_1_3");
					put(grammarAccess.getETExpressionAccess().getAlternatives(), "rule__ETExpression__Alternatives");
					put(grammarAccess.getETExpressionAccess().getAlternatives_1_0(), "rule__ETExpression__Alternatives_1_0");
					put(grammarAccess.getETImplyLogicOrExpressionAccess().getAlternatives_1_0(), "rule__ETImplyLogicOrExpression__Alternatives_1_0");
					put(grammarAccess.getETAssignmentExpressionAccess().getAlternatives_1_0(), "rule__ETAssignmentExpression__Alternatives_1_0");
					put(grammarAccess.getETEqualityExpressionAccess().getAlternatives_1_0(), "rule__ETEqualityExpression__Alternatives_1_0");
					put(grammarAccess.getETInequalityExpressionAccess().getAlternatives_1_0(), "rule__ETInequalityExpression__Alternatives_1_0");
					put(grammarAccess.getETMinMaxExpressionAccess().getAlternatives_1_0(), "rule__ETMinMaxExpression__Alternatives_1_0");
					put(grammarAccess.getETBitLeftBRightExpressionAccess().getAlternatives_1_0(), "rule__ETBitLeftBRightExpression__Alternatives_1_0");
					put(grammarAccess.getETAdditiveExpressionAccess().getAlternatives_1_0(), "rule__ETAdditiveExpression__Alternatives_1_0");
					put(grammarAccess.getETMultiplicativeExpressionAccess().getAlternatives_1_0(), "rule__ETMultiplicativeExpression__Alternatives_1_0");
					put(grammarAccess.getETPrefixExpressionAccess().getAlternatives(), "rule__ETPrefixExpression__Alternatives");
					put(grammarAccess.getETPrefixExpressionAccess().getAlternatives_1_0(), "rule__ETPrefixExpression__Alternatives_1_0");
					put(grammarAccess.getETUnaryExpressionAccess().getAlternatives(), "rule__ETUnaryExpression__Alternatives");
					put(grammarAccess.getETUnaryExpressionAccess().getAlternatives_1_0(), "rule__ETUnaryExpression__Alternatives_1_0");
					put(grammarAccess.getETPostfixExpressionAccess().getAlternatives_1(), "rule__ETPostfixExpression__Alternatives_1");
					put(grammarAccess.getETPrimaryExpressionAccess().getAlternatives(), "rule__ETPrimaryExpression__Alternatives");
					put(grammarAccess.getBOOLAccess().getAlternatives(), "rule__BOOL__Alternatives");
					put(grammarAccess.getETIOTypeAccess().getAlternatives(), "rule__ETIOType__Alternatives");
					put(grammarAccess.getETFileAccess().getGroup(), "rule__ETFile__Group__0");
					put(grammarAccess.getETImportAccess().getGroup(), "rule__ETImport__Group__0");
					put(grammarAccess.getETArrayDeclarationAccess().getGroup(), "rule__ETArrayDeclaration__Group__0");
					put(grammarAccess.getETDeclarationsAccess().getGroup(), "rule__ETDeclarations__Group__0");
					put(grammarAccess.getETDeclarationsAccess().getGroup_1(), "rule__ETDeclarations__Group_1__0");
					put(grammarAccess.getETDeclarationsAccess().getGroup_1_1(), "rule__ETDeclarations__Group_1_1__0");
					put(grammarAccess.getETTypeAccess().getGroup(), "rule__ETType__Group__0");
					put(grammarAccess.getETTypeModifiersAccess().getGroup(), "rule__ETTypeModifiers__Group__0");
					put(grammarAccess.getETVariableDeclarationAccess().getGroup(), "rule__ETVariableDeclaration__Group__0");
					put(grammarAccess.getETVariableDeclarationAccess().getGroup_2(), "rule__ETVariableDeclaration__Group_2__0");
					put(grammarAccess.getETVariableIDAccess().getGroup(), "rule__ETVariableID__Group__0");
					put(grammarAccess.getETVariableIDAccess().getGroup_3(), "rule__ETVariableID__Group_3__0");
					put(grammarAccess.getETMultiInitialiserAccess().getGroup(), "rule__ETMultiInitialiser__Group__0");
					put(grammarAccess.getETMultiInitialiserAccess().getGroup_2(), "rule__ETMultiInitialiser__Group_2__0");
					put(grammarAccess.getETTypeDeclarationAccess().getGroup(), "rule__ETTypeDeclaration__Group__0");
					put(grammarAccess.getETTypeDeclarationAccess().getGroup_3(), "rule__ETTypeDeclaration__Group_3__0");
					put(grammarAccess.getETTypeIDAccess().getGroup(), "rule__ETTypeID__Group__0");
					put(grammarAccess.getETTypeIdentifierAccess().getGroup_6(), "rule__ETTypeIdentifier__Group_6__0");
					put(grammarAccess.getETIntegerTypeAccess().getGroup(), "rule__ETIntegerType__Group__0");
					put(grammarAccess.getETIntegerTypeAccess().getGroup_2(), "rule__ETIntegerType__Group_2__0");
					put(grammarAccess.getETClockTypeAccess().getGroup(), "rule__ETClockType__Group__0");
					put(grammarAccess.getETActionTypeAccess().getGroup_2(), "rule__ETActionType__Group_2__0");
					put(grammarAccess.getETInputTypeAccess().getGroup(), "rule__ETInputType__Group__0");
					put(grammarAccess.getETOutputTypeAccess().getGroup(), "rule__ETOutputType__Group__0");
					put(grammarAccess.getETBooleanTypeAccess().getGroup(), "rule__ETBooleanType__Group__0");
					put(grammarAccess.getETScalarTypeAccess().getGroup(), "rule__ETScalarType__Group__0");
					put(grammarAccess.getETStructTypeAccess().getGroup(), "rule__ETStructType__Group__0");
					put(grammarAccess.getETStructTypeAccess().getGroup_4(), "rule__ETStructType__Group_4__0");
					put(grammarAccess.getETFieldDeclarationAccess().getGroup(), "rule__ETFieldDeclaration__Group__0");
					put(grammarAccess.getETFieldDeclarationAccess().getGroup_2(), "rule__ETFieldDeclaration__Group_2__0");
					put(grammarAccess.getETFieldIDAccess().getGroup(), "rule__ETFieldID__Group__0");
					put(grammarAccess.getETSpecificationExpressionAccess().getGroup(), "rule__ETSpecificationExpression__Group__0");
					put(grammarAccess.getETSpecificationExpressionAccess().getGroup_1(), "rule__ETSpecificationExpression__Group_1__0");
					put(grammarAccess.getETSpecificationDisjunctionExpressionAccess().getGroup(), "rule__ETSpecificationDisjunctionExpression__Group__0");
					put(grammarAccess.getETSpecificationDisjunctionExpressionAccess().getGroup_1(), "rule__ETSpecificationDisjunctionExpression__Group_1__0");
					put(grammarAccess.getETSpecificationCompositionExpressionAccess().getGroup(), "rule__ETSpecificationCompositionExpression__Group__0");
					put(grammarAccess.getETSpecificationCompositionExpressionAccess().getGroup_1(), "rule__ETSpecificationCompositionExpression__Group_1__0");
					put(grammarAccess.getETPrimarySpecificationExpressionAccess().getGroup_2(), "rule__ETPrimarySpecificationExpression__Group_2__0");
					put(grammarAccess.getETSpecificationReferenceAccess().getGroup(), "rule__ETSpecificationReference__Group__0");
					put(grammarAccess.getETSpecificationInstantiationAccess().getGroup(), "rule__ETSpecificationInstantiation__Group__0");
					put(grammarAccess.getETSpecificationInstantiationAccess().getGroup_3(), "rule__ETSpecificationInstantiation__Group_3__0");
					put(grammarAccess.getETSpecificationInstantiationAccess().getGroup_3_1(), "rule__ETSpecificationInstantiation__Group_3_1__0");
					put(grammarAccess.getETSpecificationBindingAccess().getGroup(), "rule__ETSpecificationBinding__Group__0");
					put(grammarAccess.getETSpecificationDefinitionAccess().getGroup_1(), "rule__ETSpecificationDefinition__Group_1__0");
					put(grammarAccess.getETSpecificationTemplateAccess().getGroup(), "rule__ETSpecificationTemplate__Group__0");
					put(grammarAccess.getETSpecificationTemplateAccess().getGroup_4(), "rule__ETSpecificationTemplate__Group_4__0");
					put(grammarAccess.getETSpecificationTemplateAccess().getGroup_4_1(), "rule__ETSpecificationTemplate__Group_4_1__0");
					put(grammarAccess.getETSpecificationBodyAccess().getGroup(), "rule__ETSpecificationBody__Group__0");
					put(grammarAccess.getETParameterAccess().getGroup(), "rule__ETParameter__Group__0");
					put(grammarAccess.getETLocationAccess().getGroup(), "rule__ETLocation__Group__0");
					put(grammarAccess.getETLocationAccess().getGroup_3(), "rule__ETLocation__Group_3__0");
					put(grammarAccess.getETLocationAccess().getGroup_3_2(), "rule__ETLocation__Group_3_2__0");
					put(grammarAccess.getETLocationAccess().getGroup_4(), "rule__ETLocation__Group_4__0");
					put(grammarAccess.getETLocationAccess().getGroup_4_1(), "rule__ETLocation__Group_4_1__0");
					put(grammarAccess.getETEdgeAccess().getGroup(), "rule__ETEdge__Group__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_0(), "rule__ETEdge__Group_1_0__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_0_3(), "rule__ETEdge__Group_1_0_3__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_0_8(), "rule__ETEdge__Group_1_0_8__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_0_9_0(), "rule__ETEdge__Group_1_0_9_0__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_0_9_1(), "rule__ETEdge__Group_1_0_9_1__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_0_9_1_1(), "rule__ETEdge__Group_1_0_9_1_1__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_1(), "rule__ETEdge__Group_1_1__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_1_2(), "rule__ETEdge__Group_1_1_2__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_1_3_0(), "rule__ETEdge__Group_1_1_3_0__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_1_3_1(), "rule__ETEdge__Group_1_1_3_1__0");
					put(grammarAccess.getETEdgeAccess().getGroup_1_1_3_1_1(), "rule__ETEdge__Group_1_1_3_1_1__0");
					put(grammarAccess.getETIOAccess().getGroup(), "rule__ETIO__Group__0");
					put(grammarAccess.getETSelectAccess().getGroup(), "rule__ETSelect__Group__0");
					put(grammarAccess.getETExpressionAccess().getGroup_1(), "rule__ETExpression__Group_1__0");
					put(grammarAccess.getETExpressionAccess().getGroup_1_0_0(), "rule__ETExpression__Group_1_0_0__0");
					put(grammarAccess.getETExpressionAccess().getGroup_1_0_1(), "rule__ETExpression__Group_1_0_1__0");
					put(grammarAccess.getETImplyLogicOrExpressionAccess().getGroup(), "rule__ETImplyLogicOrExpression__Group__0");
					put(grammarAccess.getETImplyLogicOrExpressionAccess().getGroup_1(), "rule__ETImplyLogicOrExpression__Group_1__0");
					put(grammarAccess.getETImplyLogicOrExpressionAccess().getGroup_1_0_0(), "rule__ETImplyLogicOrExpression__Group_1_0_0__0");
					put(grammarAccess.getETImplyLogicOrExpressionAccess().getGroup_1_0_1(), "rule__ETImplyLogicOrExpression__Group_1_0_1__0");
					put(grammarAccess.getETLogicAndExpression1Access().getGroup(), "rule__ETLogicAndExpression1__Group__0");
					put(grammarAccess.getETLogicAndExpression1Access().getGroup_1(), "rule__ETLogicAndExpression1__Group_1__0");
					put(grammarAccess.getETLogicAndExpression1Access().getGroup_1_0(), "rule__ETLogicAndExpression1__Group_1_0__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup(), "rule__ETAssignmentExpression__Group__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1(), "rule__ETAssignmentExpression__Group_1__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_0(), "rule__ETAssignmentExpression__Group_1_0_0__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_1(), "rule__ETAssignmentExpression__Group_1_0_1__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_2(), "rule__ETAssignmentExpression__Group_1_0_2__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_3(), "rule__ETAssignmentExpression__Group_1_0_3__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_4(), "rule__ETAssignmentExpression__Group_1_0_4__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_5(), "rule__ETAssignmentExpression__Group_1_0_5__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_6(), "rule__ETAssignmentExpression__Group_1_0_6__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_7(), "rule__ETAssignmentExpression__Group_1_0_7__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_8(), "rule__ETAssignmentExpression__Group_1_0_8__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_9(), "rule__ETAssignmentExpression__Group_1_0_9__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_10(), "rule__ETAssignmentExpression__Group_1_0_10__0");
					put(grammarAccess.getETAssignmentExpressionAccess().getGroup_1_0_11(), "rule__ETAssignmentExpression__Group_1_0_11__0");
					put(grammarAccess.getETConditionalExpressionAccess().getGroup(), "rule__ETConditionalExpression__Group__0");
					put(grammarAccess.getETConditionalExpressionAccess().getGroup_1(), "rule__ETConditionalExpression__Group_1__0");
					put(grammarAccess.getETLogicOrExpression2Access().getGroup(), "rule__ETLogicOrExpression2__Group__0");
					put(grammarAccess.getETLogicOrExpression2Access().getGroup_1(), "rule__ETLogicOrExpression2__Group_1__0");
					put(grammarAccess.getETLogicOrExpression2Access().getGroup_1_0(), "rule__ETLogicOrExpression2__Group_1_0__0");
					put(grammarAccess.getETLogicAndExpression2Access().getGroup(), "rule__ETLogicAndExpression2__Group__0");
					put(grammarAccess.getETLogicAndExpression2Access().getGroup_1(), "rule__ETLogicAndExpression2__Group_1__0");
					put(grammarAccess.getETLogicAndExpression2Access().getGroup_1_0(), "rule__ETLogicAndExpression2__Group_1_0__0");
					put(grammarAccess.getETBitOrExpressionAccess().getGroup(), "rule__ETBitOrExpression__Group__0");
					put(grammarAccess.getETBitOrExpressionAccess().getGroup_1(), "rule__ETBitOrExpression__Group_1__0");
					put(grammarAccess.getETBitOrExpressionAccess().getGroup_1_0(), "rule__ETBitOrExpression__Group_1_0__0");
					put(grammarAccess.getETBitXORExpressionAccess().getGroup(), "rule__ETBitXORExpression__Group__0");
					put(grammarAccess.getETBitXORExpressionAccess().getGroup_1(), "rule__ETBitXORExpression__Group_1__0");
					put(grammarAccess.getETBitXORExpressionAccess().getGroup_1_0(), "rule__ETBitXORExpression__Group_1_0__0");
					put(grammarAccess.getETBitAndExpressionAccess().getGroup(), "rule__ETBitAndExpression__Group__0");
					put(grammarAccess.getETBitAndExpressionAccess().getGroup_1(), "rule__ETBitAndExpression__Group_1__0");
					put(grammarAccess.getETBitAndExpressionAccess().getGroup_1_0(), "rule__ETBitAndExpression__Group_1_0__0");
					put(grammarAccess.getETEqualityExpressionAccess().getGroup(), "rule__ETEqualityExpression__Group__0");
					put(grammarAccess.getETEqualityExpressionAccess().getGroup_1(), "rule__ETEqualityExpression__Group_1__0");
					put(grammarAccess.getETEqualityExpressionAccess().getGroup_1_0_0(), "rule__ETEqualityExpression__Group_1_0_0__0");
					put(grammarAccess.getETEqualityExpressionAccess().getGroup_1_0_1(), "rule__ETEqualityExpression__Group_1_0_1__0");
					put(grammarAccess.getETInequalityExpressionAccess().getGroup(), "rule__ETInequalityExpression__Group__0");
					put(grammarAccess.getETInequalityExpressionAccess().getGroup_1(), "rule__ETInequalityExpression__Group_1__0");
					put(grammarAccess.getETInequalityExpressionAccess().getGroup_1_0_0(), "rule__ETInequalityExpression__Group_1_0_0__0");
					put(grammarAccess.getETInequalityExpressionAccess().getGroup_1_0_1(), "rule__ETInequalityExpression__Group_1_0_1__0");
					put(grammarAccess.getETInequalityExpressionAccess().getGroup_1_0_2(), "rule__ETInequalityExpression__Group_1_0_2__0");
					put(grammarAccess.getETInequalityExpressionAccess().getGroup_1_0_3(), "rule__ETInequalityExpression__Group_1_0_3__0");
					put(grammarAccess.getETMinMaxExpressionAccess().getGroup(), "rule__ETMinMaxExpression__Group__0");
					put(grammarAccess.getETMinMaxExpressionAccess().getGroup_1(), "rule__ETMinMaxExpression__Group_1__0");
					put(grammarAccess.getETMinMaxExpressionAccess().getGroup_1_0_0(), "rule__ETMinMaxExpression__Group_1_0_0__0");
					put(grammarAccess.getETMinMaxExpressionAccess().getGroup_1_0_1(), "rule__ETMinMaxExpression__Group_1_0_1__0");
					put(grammarAccess.getETBitLeftBRightExpressionAccess().getGroup(), "rule__ETBitLeftBRightExpression__Group__0");
					put(grammarAccess.getETBitLeftBRightExpressionAccess().getGroup_1(), "rule__ETBitLeftBRightExpression__Group_1__0");
					put(grammarAccess.getETBitLeftBRightExpressionAccess().getGroup_1_0_0(), "rule__ETBitLeftBRightExpression__Group_1_0_0__0");
					put(grammarAccess.getETBitLeftBRightExpressionAccess().getGroup_1_0_1(), "rule__ETBitLeftBRightExpression__Group_1_0_1__0");
					put(grammarAccess.getETAdditiveExpressionAccess().getGroup(), "rule__ETAdditiveExpression__Group__0");
					put(grammarAccess.getETAdditiveExpressionAccess().getGroup_1(), "rule__ETAdditiveExpression__Group_1__0");
					put(grammarAccess.getETAdditiveExpressionAccess().getGroup_1_0_0(), "rule__ETAdditiveExpression__Group_1_0_0__0");
					put(grammarAccess.getETAdditiveExpressionAccess().getGroup_1_0_1(), "rule__ETAdditiveExpression__Group_1_0_1__0");
					put(grammarAccess.getETMultiplicativeExpressionAccess().getGroup(), "rule__ETMultiplicativeExpression__Group__0");
					put(grammarAccess.getETMultiplicativeExpressionAccess().getGroup_1(), "rule__ETMultiplicativeExpression__Group_1__0");
					put(grammarAccess.getETMultiplicativeExpressionAccess().getGroup_1_0_0(), "rule__ETMultiplicativeExpression__Group_1_0_0__0");
					put(grammarAccess.getETMultiplicativeExpressionAccess().getGroup_1_0_1(), "rule__ETMultiplicativeExpression__Group_1_0_1__0");
					put(grammarAccess.getETMultiplicativeExpressionAccess().getGroup_1_0_2(), "rule__ETMultiplicativeExpression__Group_1_0_2__0");
					put(grammarAccess.getETPrefixExpressionAccess().getGroup_1(), "rule__ETPrefixExpression__Group_1__0");
					put(grammarAccess.getETPrefixExpressionAccess().getGroup_1_0_0(), "rule__ETPrefixExpression__Group_1_0_0__0");
					put(grammarAccess.getETPrefixExpressionAccess().getGroup_1_0_1(), "rule__ETPrefixExpression__Group_1_0_1__0");
					put(grammarAccess.getETUnaryExpressionAccess().getGroup_1(), "rule__ETUnaryExpression__Group_1__0");
					put(grammarAccess.getETUnaryExpressionAccess().getGroup_1_0_0(), "rule__ETUnaryExpression__Group_1_0_0__0");
					put(grammarAccess.getETUnaryExpressionAccess().getGroup_1_0_1(), "rule__ETUnaryExpression__Group_1_0_1__0");
					put(grammarAccess.getETPostfixExpressionAccess().getGroup(), "rule__ETPostfixExpression__Group__0");
					put(grammarAccess.getETPostfixExpressionAccess().getGroup_1_0(), "rule__ETPostfixExpression__Group_1_0__0");
					put(grammarAccess.getETPostfixExpressionAccess().getGroup_1_1(), "rule__ETPostfixExpression__Group_1_1__0");
					put(grammarAccess.getETStructExpressionAccess().getGroup(), "rule__ETStructExpression__Group__0");
					put(grammarAccess.getETStructExpressionAccess().getGroup_1(), "rule__ETStructExpression__Group_1__0");
					put(grammarAccess.getETArrayExpressionAccess().getGroup(), "rule__ETArrayExpression__Group__0");
					put(grammarAccess.getETArrayExpressionAccess().getGroup_1(), "rule__ETArrayExpression__Group_1__0");
					put(grammarAccess.getETReferenceAccess().getGroup(), "rule__ETReference__Group__0");
					put(grammarAccess.getETBooleanLiteralAccess().getGroup(), "rule__ETBooleanLiteral__Group__0");
					put(grammarAccess.getETNumberLiteralAccess().getGroup(), "rule__ETNumberLiteral__Group__0");
					put(grammarAccess.getETParenthesizedExpressionAccess().getGroup(), "rule__ETParenthesizedExpression__Group__0");
					put(grammarAccess.getETFileAccess().getImportsAssignment_1(), "rule__ETFile__ImportsAssignment_1");
					put(grammarAccess.getETFileAccess().getDeclarationsAssignment_2(), "rule__ETFile__DeclarationsAssignment_2");
					put(grammarAccess.getETFileAccess().getSpecificationsAssignment_3(), "rule__ETFile__SpecificationsAssignment_3");
					put(grammarAccess.getETImportAccess().getImportedNamespaceAssignment_1(), "rule__ETImport__ImportedNamespaceAssignment_1");
					put(grammarAccess.getETArrayDeclarationAccess().getSizeAssignment_1(), "rule__ETArrayDeclaration__SizeAssignment_1");
					put(grammarAccess.getETDeclarationsAccess().getDeclarationsAssignment_1_0(), "rule__ETDeclarations__DeclarationsAssignment_1_0");
					put(grammarAccess.getETDeclarationsAccess().getDeclarationsAssignment_1_1_1(), "rule__ETDeclarations__DeclarationsAssignment_1_1_1");
					put(grammarAccess.getETTypeAccess().getModifiersAssignment_0(), "rule__ETType__ModifiersAssignment_0");
					put(grammarAccess.getETTypeAccess().getIdentifierAssignment_1(), "rule__ETType__IdentifierAssignment_1");
					put(grammarAccess.getETTypeModifiersAccess().getUrgentAssignment_1_0(), "rule__ETTypeModifiers__UrgentAssignment_1_0");
					put(grammarAccess.getETTypeModifiersAccess().getMetaAssignment_1_1(), "rule__ETTypeModifiers__MetaAssignment_1_1");
					put(grammarAccess.getETTypeModifiersAccess().getConstAssignment_1_2(), "rule__ETTypeModifiers__ConstAssignment_1_2");
					put(grammarAccess.getETVariableDeclarationAccess().getTypeAssignment_0(), "rule__ETVariableDeclaration__TypeAssignment_0");
					put(grammarAccess.getETVariableDeclarationAccess().getVariablesAssignment_1(), "rule__ETVariableDeclaration__VariablesAssignment_1");
					put(grammarAccess.getETVariableDeclarationAccess().getVariablesAssignment_2_1(), "rule__ETVariableDeclaration__VariablesAssignment_2_1");
					put(grammarAccess.getETVariableIDAccess().getNameAssignment_0(), "rule__ETVariableID__NameAssignment_0");
					put(grammarAccess.getETVariableIDAccess().getIoTypeAssignment_1(), "rule__ETVariableID__IoTypeAssignment_1");
					put(grammarAccess.getETVariableIDAccess().getDimensionsAssignment_2(), "rule__ETVariableID__DimensionsAssignment_2");
					put(grammarAccess.getETVariableIDAccess().getInitialiserAssignment_3_1(), "rule__ETVariableID__InitialiserAssignment_3_1");
					put(grammarAccess.getETSingleInitialiserAccess().getExpressionAssignment(), "rule__ETSingleInitialiser__ExpressionAssignment");
					put(grammarAccess.getETMultiInitialiserAccess().getInitialisersAssignment_1(), "rule__ETMultiInitialiser__InitialisersAssignment_1");
					put(grammarAccess.getETMultiInitialiserAccess().getInitialisersAssignment_2_1(), "rule__ETMultiInitialiser__InitialisersAssignment_2_1");
					put(grammarAccess.getETTypeDeclarationAccess().getBaseTypeAssignment_1(), "rule__ETTypeDeclaration__BaseTypeAssignment_1");
					put(grammarAccess.getETTypeDeclarationAccess().getTypesAssignment_2(), "rule__ETTypeDeclaration__TypesAssignment_2");
					put(grammarAccess.getETTypeDeclarationAccess().getTypesAssignment_3_1(), "rule__ETTypeDeclaration__TypesAssignment_3_1");
					put(grammarAccess.getETTypeIDAccess().getNameAssignment_0(), "rule__ETTypeID__NameAssignment_0");
					put(grammarAccess.getETTypeIDAccess().getDimensionsAssignment_1(), "rule__ETTypeID__DimensionsAssignment_1");
					put(grammarAccess.getETTypeIdentifierAccess().getTargetAssignment_6_1(), "rule__ETTypeIdentifier__TargetAssignment_6_1");
					put(grammarAccess.getETIntegerTypeAccess().getMinAssignment_2_1(), "rule__ETIntegerType__MinAssignment_2_1");
					put(grammarAccess.getETIntegerTypeAccess().getMaxAssignment_2_3(), "rule__ETIntegerType__MaxAssignment_2_3");
					put(grammarAccess.getETScalarTypeAccess().getSizeAssignment_3(), "rule__ETScalarType__SizeAssignment_3");
					put(grammarAccess.getETStructTypeAccess().getDeclarationsAssignment_3(), "rule__ETStructType__DeclarationsAssignment_3");
					put(grammarAccess.getETStructTypeAccess().getDeclarationsAssignment_4_1(), "rule__ETStructType__DeclarationsAssignment_4_1");
					put(grammarAccess.getETFieldDeclarationAccess().getTypeAssignment_0(), "rule__ETFieldDeclaration__TypeAssignment_0");
					put(grammarAccess.getETFieldDeclarationAccess().getFieldsAssignment_1(), "rule__ETFieldDeclaration__FieldsAssignment_1");
					put(grammarAccess.getETFieldDeclarationAccess().getFieldsAssignment_2_1(), "rule__ETFieldDeclaration__FieldsAssignment_2_1");
					put(grammarAccess.getETFieldIDAccess().getNameAssignment_0(), "rule__ETFieldID__NameAssignment_0");
					put(grammarAccess.getETFieldIDAccess().getIoTypeAssignment_1(), "rule__ETFieldID__IoTypeAssignment_1");
					put(grammarAccess.getETFieldIDAccess().getDimensionsAssignment_2(), "rule__ETFieldID__DimensionsAssignment_2");
					put(grammarAccess.getETSpecificationExpressionAccess().getRightAssignment_1_2(), "rule__ETSpecificationExpression__RightAssignment_1_2");
					put(grammarAccess.getETSpecificationDisjunctionExpressionAccess().getRightAssignment_1_2(), "rule__ETSpecificationDisjunctionExpression__RightAssignment_1_2");
					put(grammarAccess.getETSpecificationCompositionExpressionAccess().getRightAssignment_1_2(), "rule__ETSpecificationCompositionExpression__RightAssignment_1_2");
					put(grammarAccess.getETSpecificationReferenceAccess().getSpecificationAssignment_1(), "rule__ETSpecificationReference__SpecificationAssignment_1");
					put(grammarAccess.getETSpecificationInstantiationAccess().getTemplateAssignment_1(), "rule__ETSpecificationInstantiation__TemplateAssignment_1");
					put(grammarAccess.getETSpecificationInstantiationAccess().getArgumentsAssignment_3_0(), "rule__ETSpecificationInstantiation__ArgumentsAssignment_3_0");
					put(grammarAccess.getETSpecificationInstantiationAccess().getArgumentsAssignment_3_1_1(), "rule__ETSpecificationInstantiation__ArgumentsAssignment_3_1_1");
					put(grammarAccess.getETSpecificationBindingAccess().getNameAssignment_1(), "rule__ETSpecificationBinding__NameAssignment_1");
					put(grammarAccess.getETSpecificationBindingAccess().getExpressionAssignment_3(), "rule__ETSpecificationBinding__ExpressionAssignment_3");
					put(grammarAccess.getETSpecificationDefinitionAccess().getNameAssignment_1_2(), "rule__ETSpecificationDefinition__NameAssignment_1_2");
					put(grammarAccess.getETSpecificationDefinitionAccess().getBodyAssignment_1_3(), "rule__ETSpecificationDefinition__BodyAssignment_1_3");
					put(grammarAccess.getETSpecificationTemplateAccess().getNameAssignment_2(), "rule__ETSpecificationTemplate__NameAssignment_2");
					put(grammarAccess.getETSpecificationTemplateAccess().getParametersAssignment_4_0(), "rule__ETSpecificationTemplate__ParametersAssignment_4_0");
					put(grammarAccess.getETSpecificationTemplateAccess().getParametersAssignment_4_1_1(), "rule__ETSpecificationTemplate__ParametersAssignment_4_1_1");
					put(grammarAccess.getETSpecificationTemplateAccess().getBodyAssignment_6(), "rule__ETSpecificationTemplate__BodyAssignment_6");
					put(grammarAccess.getETSpecificationBodyAccess().getDeclarationsAssignment_1(), "rule__ETSpecificationBody__DeclarationsAssignment_1");
					put(grammarAccess.getETSpecificationBodyAccess().getInitialLocationAssignment_3(), "rule__ETSpecificationBody__InitialLocationAssignment_3");
					put(grammarAccess.getETSpecificationBodyAccess().getLocationsAssignment_4(), "rule__ETSpecificationBody__LocationsAssignment_4");
					put(grammarAccess.getETParameterAccess().getTypeAssignment_0(), "rule__ETParameter__TypeAssignment_0");
					put(grammarAccess.getETParameterAccess().getNameAssignment_1(), "rule__ETParameter__NameAssignment_1");
					put(grammarAccess.getETParameterAccess().getIoTypeAssignment_2(), "rule__ETParameter__IoTypeAssignment_2");
					put(grammarAccess.getETParameterAccess().getDimensionsAssignment_3(), "rule__ETParameter__DimensionsAssignment_3");
					put(grammarAccess.getETLocationAccess().getUrgentAssignment_0_0(), "rule__ETLocation__UrgentAssignment_0_0");
					put(grammarAccess.getETLocationAccess().getUniversalAssignment_0_1(), "rule__ETLocation__UniversalAssignment_0_1");
					put(grammarAccess.getETLocationAccess().getNameAssignment_1(), "rule__ETLocation__NameAssignment_1");
					put(grammarAccess.getETLocationAccess().getInvariantsAssignment_3_1(), "rule__ETLocation__InvariantsAssignment_3_1");
					put(grammarAccess.getETLocationAccess().getInvariantsAssignment_3_2_1(), "rule__ETLocation__InvariantsAssignment_3_2_1");
					put(grammarAccess.getETLocationAccess().getEdgesAssignment_4_0(), "rule__ETLocation__EdgesAssignment_4_0");
					put(grammarAccess.getETLocationAccess().getEdgesAssignment_4_1_1(), "rule__ETLocation__EdgesAssignment_4_1_1");
					put(grammarAccess.getETEdgeAccess().getControllableAssignment_0(), "rule__ETEdge__ControllableAssignment_0");
					put(grammarAccess.getETEdgeAccess().getSelectsAssignment_1_0_2(), "rule__ETEdge__SelectsAssignment_1_0_2");
					put(grammarAccess.getETEdgeAccess().getSelectsAssignment_1_0_3_1(), "rule__ETEdge__SelectsAssignment_1_0_3_1");
					put(grammarAccess.getETEdgeAccess().getIoAssignment_1_0_6(), "rule__ETEdge__IoAssignment_1_0_6");
					put(grammarAccess.getETEdgeAccess().getGuardAssignment_1_0_8_2(), "rule__ETEdge__GuardAssignment_1_0_8_2");
					put(grammarAccess.getETEdgeAccess().getTargetAssignment_1_0_9_0_1(), "rule__ETEdge__TargetAssignment_1_0_9_0_1");
					put(grammarAccess.getETEdgeAccess().getUpdatesAssignment_1_0_9_1_1_0(), "rule__ETEdge__UpdatesAssignment_1_0_9_1_1_0");
					put(grammarAccess.getETEdgeAccess().getTargetAssignment_1_0_9_1_3(), "rule__ETEdge__TargetAssignment_1_0_9_1_3");
					put(grammarAccess.getETEdgeAccess().getIoAssignment_1_1_0(), "rule__ETEdge__IoAssignment_1_1_0");
					put(grammarAccess.getETEdgeAccess().getGuardAssignment_1_1_2_2(), "rule__ETEdge__GuardAssignment_1_1_2_2");
					put(grammarAccess.getETEdgeAccess().getTargetAssignment_1_1_3_0_1(), "rule__ETEdge__TargetAssignment_1_1_3_0_1");
					put(grammarAccess.getETEdgeAccess().getUpdatesAssignment_1_1_3_1_1_0(), "rule__ETEdge__UpdatesAssignment_1_1_3_1_1_0");
					put(grammarAccess.getETEdgeAccess().getTargetAssignment_1_1_3_1_3(), "rule__ETEdge__TargetAssignment_1_1_3_1_3");
					put(grammarAccess.getETIOAccess().getExpressionAssignment_0(), "rule__ETIO__ExpressionAssignment_0");
					put(grammarAccess.getETIOAccess().getTypeAssignment_1(), "rule__ETIO__TypeAssignment_1");
					put(grammarAccess.getETSelectAccess().getNameAssignment_0(), "rule__ETSelect__NameAssignment_0");
					put(grammarAccess.getETSelectAccess().getTypeAssignment_2(), "rule__ETSelect__TypeAssignment_2");
					put(grammarAccess.getETExpressionAccess().getNameAssignment_1_2(), "rule__ETExpression__NameAssignment_1_2");
					put(grammarAccess.getETExpressionAccess().getTypeAssignment_1_4(), "rule__ETExpression__TypeAssignment_1_4");
					put(grammarAccess.getETExpressionAccess().getExpressionAssignment_1_6(), "rule__ETExpression__ExpressionAssignment_1_6");
					put(grammarAccess.getETImplyLogicOrExpressionAccess().getRightAssignment_1_1(), "rule__ETImplyLogicOrExpression__RightAssignment_1_1");
					put(grammarAccess.getETLogicAndExpression1Access().getRightAssignment_1_1(), "rule__ETLogicAndExpression1__RightAssignment_1_1");
					put(grammarAccess.getETAssignmentExpressionAccess().getRightAssignment_1_1(), "rule__ETAssignmentExpression__RightAssignment_1_1");
					put(grammarAccess.getETConditionalExpressionAccess().getThenAssignment_1_2(), "rule__ETConditionalExpression__ThenAssignment_1_2");
					put(grammarAccess.getETConditionalExpressionAccess().getElseAssignment_1_4(), "rule__ETConditionalExpression__ElseAssignment_1_4");
					put(grammarAccess.getETLogicOrExpression2Access().getRightAssignment_1_1(), "rule__ETLogicOrExpression2__RightAssignment_1_1");
					put(grammarAccess.getETLogicAndExpression2Access().getRightAssignment_1_1(), "rule__ETLogicAndExpression2__RightAssignment_1_1");
					put(grammarAccess.getETBitOrExpressionAccess().getRightAssignment_1_1(), "rule__ETBitOrExpression__RightAssignment_1_1");
					put(grammarAccess.getETBitXORExpressionAccess().getRightAssignment_1_1(), "rule__ETBitXORExpression__RightAssignment_1_1");
					put(grammarAccess.getETBitAndExpressionAccess().getRightAssignment_1_1(), "rule__ETBitAndExpression__RightAssignment_1_1");
					put(grammarAccess.getETEqualityExpressionAccess().getRightAssignment_1_1(), "rule__ETEqualityExpression__RightAssignment_1_1");
					put(grammarAccess.getETInequalityExpressionAccess().getRightAssignment_1_1(), "rule__ETInequalityExpression__RightAssignment_1_1");
					put(grammarAccess.getETMinMaxExpressionAccess().getRightAssignment_1_1(), "rule__ETMinMaxExpression__RightAssignment_1_1");
					put(grammarAccess.getETBitLeftBRightExpressionAccess().getRightAssignment_1_1(), "rule__ETBitLeftBRightExpression__RightAssignment_1_1");
					put(grammarAccess.getETAdditiveExpressionAccess().getRightAssignment_1_1(), "rule__ETAdditiveExpression__RightAssignment_1_1");
					put(grammarAccess.getETMultiplicativeExpressionAccess().getRightAssignment_1_1(), "rule__ETMultiplicativeExpression__RightAssignment_1_1");
					put(grammarAccess.getETPrefixExpressionAccess().getExpressionAssignment_1_1(), "rule__ETPrefixExpression__ExpressionAssignment_1_1");
					put(grammarAccess.getETUnaryExpressionAccess().getExpressionAssignment_1_1(), "rule__ETUnaryExpression__ExpressionAssignment_1_1");
					put(grammarAccess.getETStructExpressionAccess().getRightAssignment_1_2(), "rule__ETStructExpression__RightAssignment_1_2");
					put(grammarAccess.getETArrayExpressionAccess().getRightAssignment_1_2(), "rule__ETArrayExpression__RightAssignment_1_2");
					put(grammarAccess.getETReferenceAccess().getTargetAssignment_1(), "rule__ETReference__TargetAssignment_1");
					put(grammarAccess.getETBooleanLiteralAccess().getValueAssignment_1(), "rule__ETBooleanLiteral__ValueAssignment_1");
					put(grammarAccess.getETNumberLiteralAccess().getValueAssignment_1(), "rule__ETNumberLiteral__ValueAssignment_1");
					put(grammarAccess.getETTypeModifiersAccess().getUnorderedGroup_1(), "rule__ETTypeModifiers__UnorderedGroup_1");
					put(grammarAccess.getETLocationAccess().getUnorderedGroup_0(), "rule__ETLocation__UnorderedGroup_0");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			dk.itu.ecdar.text.ui.contentassist.antlr.internal.InternalEcdarTextParser typedParser = (dk.itu.ecdar.text.ui.contentassist.antlr.internal.InternalEcdarTextParser) parser;
			typedParser.entryRuleETFile();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EcdarTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EcdarTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
