/*
 * generated by Xtext
 */
package dk.itu.ecdar.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EcdarTextUiModule extends dk.itu.ecdar.text.ui.AbstractEcdarTextUiModule {
	public EcdarTextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
