/*
* generated by Xtext
*/
package dk.itu.ecdar.text.ui.contentassist;

import dk.itu.ecdar.text.ui.contentassist.AbstractEcdarTextProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EcdarTextProposalProvider extends AbstractEcdarTextProposalProvider {

}
