/*
 * generated by Xtext
 */
package dk.itu.ecdar.text.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.itu.ecdar.text.ui.internal.EcdarTextActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EcdarTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EcdarTextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EcdarTextActivator.getInstance().getInjector(EcdarTextActivator.DK_ITU_ECDAR_TEXT_ECDARTEXT);
	}
	
}
